---
title: "Assignment 3"
author: "Amy Gardiner"
date: "12/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tidy Data and Iteration 
```{r, echo=FALSE}
library(tidyverse)

impute_by_median<-function(x){
  
  mu<-median(x,na.rm=1) # first compute the median of x
  
  impute_f<-function(z){ # coordinate-wise imputation
    if(is.na(z)){
      return(mu) # if z is na replace with median
    }else{
      return(z) # otherwise leave in lace
    }
  }
  return(map_dbl(x,impute_f)) # apply the map function to impute across vector
}

v<-c(1,2,NA,4)
impute_by_median(v)

x<-c(seq(0,10,0.1))
y<-c(seq(1,51,0.5))
df_xy<-data.frame(x,y)
df_xy%>%head(5)

df_xy%>%
  mutate(z=map2_dbl(x,y,~.x+.y)) %>%
  head(5)
  
sometimes_missing<-function(index,value){
  if(index%%5==0){
    return(NA)
  }else{
    return(value)
  }
}

sometimes_missing(14,25)
sometimes_missing(15,25)

df_xy_missing<-data.frame(x,y)
df_xy_missing%>%
  select(x) %>%
  mutate(z=map2_dbl(row_number(y),y,sometimes_missing)) %>%
  rename(y=z) %>%
  head(10)

df_xy_impute<-data.frame(x,y=impute_by_median(map2_dbl(row_number(y),y,sometimes_missing)))
df_xy_impute%>%
  head(10)

df_xy<-df_xy%>%
  mutate(source="original")

df_xy_missing<-df_xy_missing%>%
  mutate(source="corrupted")

df_xy_impute<-df_xy_impute%>%
  mutate(source="imputed")

df_combined<-rbind(df_xy,df_xy_missing,df_xy_impute)

ggplot(df_combined,aes(x=x,y=y,color=source))+geom_point()+facet_wrap(~source)+geom_smooth(method="lm")
```

Using the readxl library
```{r,echo=FALSE}
library(readxl)
#folder_path<-""   already within this directory
file_name<-"HockeyLeague.xlsx"
#file_path<-paste(folder_path,file_name,sep="")
wins_data_frame<-read_excel(file_name,sheet="Wins")
wins_data_frame %>%
  select(1:5) %>%
  head(3)

years<-seq(1990,2020,1)
years<-c(as.character(years))

wins_tidy<-wins_data_frame %>%
  pivot_longer(cols=(all_of(years)),names_to="Year",values_to="Values") %>%
  separate(Values,into=c("Wins","Total"),sep=" of ", convert=TRUE) %>%
  rename(Team=...1)

dim(wins_tidy)
head(wins_tidy,5)

losses_data_frame<-read_excel(file_name,sheet="Losses")
losses_tidy<-losses_data_frame %>%
  pivot_longer(cols=(all_of(years)),names_to="Year",values_to="Values") %>%
  separate(Values,into=c("Losses","Total"),sep=" of ", convert=TRUE) %>%
  rename(Team=...1) %>%
  head(5)

hockey_df<-inner_join(wins_tidy,losses_tidy, by=c("Team","Year","Total"))
hockey_df %>% mutate(Draws=Total-Wins-Losses,Wins_rt=Wins/Total,Losses_rt=Losses/Total,Draws_rt=Draws/Total)

```


