---
title: "Assignment 8"
author: "Amy Gardiner"
date: "22/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(Stat2Data)
library(palmerpenguins)
```

## An unpaired t test

```{r}
peng_AC<-penguins%>%
  drop_na(species,body_mass_g)%>%
  filter(species!="Gentoo")

t_test_function<-function(data,group_col,val_col,var_equal=TRUE){
  
  names(data)[names(data)==group_col] <- "group_col"
  names(data)[names(data)==val_col] <- "val_col"
  # very important here for tidyverse functionality to work
  
  mean_0<-data%>%
    filter(group_col=="Adelie")%>%
    pull(val_col)%>%
    mean() #compute mean of first group
  
  mean_1<-data%>%
    filter(group_col=="Chinstrap")%>%
    pull(val_col)%>%
    mean() #compute mean of second group
  
  sd_0<-data%>%
    filter(group_col=="Adelie")%>%
    pull(val_col)%>%
    sd() #compute sd of first group
    
  sd_1<-data%>%
    filter(group_col=="Chinstrap")%>%
    pull(val_col)%>%
    sd() #compute sd of second group
  
  n_0<-data%>%
    filter(group_col=="Adelie")%>%
    nrow() #compute number in first group
  
  n_1<-data%>%
    filter(group_col=="Chinstrap")%>%
    nrow() #compute number in second group
  
  sd_combined<-sqrt(((n_0-1)*sd_0^2+(n_1-1)*sd_1^2)/(n_0+n_1-2)) #compute combined sd
  
  t_statistic<-(mean_0-mean_1)/(sd_combined*sqrt(1/n_0+1/n_1))
  
  p_value<-2*(1-pt(abs(t_statistic),df=n_0+n_1-2))
  
  return(data.frame(t_stat=t_statistic,dof=n_0+n_1-2,p_val=p_value))
}

t_test_function(data=peng_AC,val_col="body_mass_g",group_col="species")

mean_test<-peng_AC%>%
    filter(species=="Adelie")%>%
    pull(body_mass_g)%>%
    mean()

mean_test
```









